



BCP bc1..Person in C:\RepGit\Roxpartner\Person.Person.csv -U carga_dw -P cxwA@9wx1 -t";"  -S tcp:servidorleo1.database.windows.net -c -C"ACP"
BCP bc1..ProductionProduct in C:\EngenharioDados\Production.Product.csv -U carga_dw -P cxwA@9wx1 -t";"  -S tcp:servidorleo1.database.windows.net -c -C"ACP"
BCP bc1..SalesCustomer in C:\EngenharioDados\Sales.Customer.csv -U carga_dw -P cxwA@9wx1 -t";"  -S tcp:servidorleo1.database.windows.net -c -C"ACP"
BCP bc1..SalesSalesOrderDetail in C:\EngenharioDados\Sales.SalesOrderDetail.csv -U carga_dw -P cxwA@9wx1 -t";"  -S tcp:servidorleo1.database.windows.net -c -C"ACP"
BCP bc1..SalesSalesOrderHeader in C:\EngenharioDados\Sales.SalesOrderHeader.csv -U carga_dw -P cxwA@9wx1 -t";"  -S tcp:servidorleo1.database.windows.net -c -C"ACP"
BCP bc1..SalesSpecialOfferProduct in C:\EngenharioDados\Sales.SpecialOfferProduct.csv -U carga_dw -P cxwA@9wx1 -t";"  -S tcp:servidorleo1.database.windows.net -c -C"ACP"





